name: check_ig_token_expiration
on:
  workflow_dispatch
  schedule:
    - cron:  '22 7 * * *' # UTC, so 7:07pm in Japan

jobs:
  check_ig_token_expiration:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Check token expiration
      env:
        IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
      run: ./check_token_expiration.sh
