name: upload_photo
on:
  workflow_dispatch:
  schedule:
    - cron:  '7 7 * * *' # UTC, so 4:07pm in Japan

jobs:
  upload_photo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Upload photos
      env:
        IG_ACCOUNT_ID: ${{ secrets.IG_ACCOUNT_ID }}
        IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
      run: ./upload_photo.sh
